import { storagePut } from "./storage";
import { nanoid } from "nanoid";
// Gemini API key is available as GEMINI_API_KEY environment variable

export interface GenerateThumbnailParams {
  niche: string;
  productInfo: string;
  style?: "photorealistic" | "illustrated" | "minimal";
}

export interface GenerateThumbnailResult {
  imageUrl: string;
  s3Key: string;
  s3Url: string;
  prompt: string;
}

/**
 * Generate YouTube ad thumbnail using Gemini Imagen 4.0
 */
export async function generateThumbnail(
  params: GenerateThumbnailParams
): Promise<GenerateThumbnailResult> {
  const { niche, productInfo, style = "photorealistic" } = params;

  try {
    console.log("[Gemini Imagen] Generating thumbnail for niche:", niche);

    // Create thumbnail prompt based on niche and style
    const prompt = createThumbnailPrompt(niche, productInfo, style);
    console.log("[Gemini Imagen] Thumbnail prompt:", prompt);

    // Call Gemini Imagen REST API
    const response = await fetch(
      "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict",
      {
        method: "POST",
        headers: {
          "x-goog-api-key": process.env.GEMINI_API_KEY || "",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          instances: [
            {
              prompt: prompt,
            },
          ],
          parameters: {
            sampleCount: 1,
            aspectRatio: "16:9", // YouTube thumbnail aspect ratio
            personGeneration: "allow_adult",
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini Imagen API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log("[Gemini Imagen] Response received");

    if (!data.predictions || data.predictions.length === 0) {
      throw new Error("No images generated by Gemini Imagen");
    }

    // Extract base64 image from response
    const prediction = data.predictions[0];
    const base64Image = prediction.bytesBase64Encoded;

    if (!base64Image) {
      throw new Error("No image data in Gemini Imagen response");
    }

    // Convert base64 to buffer
    const imageBuffer = Buffer.from(base64Image, "base64");

    // Upload to S3
    const s3Key = `thumbnails/${niche}/${nanoid()}.jpg`;
    const { url: s3Url } = await storagePut(s3Key, imageBuffer, "image/jpeg");

    console.log("[Gemini Imagen] Thumbnail uploaded to S3:", s3Url);

    return {
      imageUrl: s3Url,
      s3Key,
      s3Url,
      prompt,
    };
  } catch (error) {
    console.error("[Gemini Imagen] Thumbnail generation failed:", error);
    throw new Error(
      `Gemini Imagen thumbnail generation failed: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

/**
 * Create thumbnail prompt based on niche and style
 */
function createThumbnailPrompt(
  niche: string,
  productInfo: string,
  style: string
): string {
  const styleDescriptor = {
    photorealistic: "photorealistic, professional photography, high quality, sharp focus",
    illustrated: "digital illustration, vibrant colors, modern art style, clean composition",
    minimal: "minimalist design, clean aesthetic, simple composition, professional",
  }[style];

  const nichePrompts: Record<string, string> = {
    manifestation: `A captivating photo of a person in deep meditation with eyes closed, surrounded by soft ethereal glowing energy waves and neural pathway visualizations. ${styleDescriptor}. Inspirational mood with deep purples, golds, and blues. Soft mystical lighting. Close-up composition showing peaceful expression. 16:9 aspect ratio for YouTube thumbnail.`,

    woodworking: `A professional photo of hands crafting a beautiful wooden piece in a workshop, with woodworking tools visible and sawdust particles catching golden light. ${styleDescriptor}. Warm browns and natural wood tones. Dynamic angle showing craftsmanship in action. Workshop setting with professional lighting. 16:9 aspect ratio for YouTube thumbnail.`,

    prepping: `A well-organized display of emergency preparedness supplies and survival gear arranged professionally. ${styleDescriptor}. Earthy tones with tactical greens. Clean product photography style showing self-sufficient systems. Natural outdoor lighting. Professional composition. 16:9 aspect ratio for YouTube thumbnail.`,

    health: `A vibrant photo showing an active, healthy lifestyle scene with energetic movement and vitality. ${styleDescriptor}. Bright energetic colors with natural lighting. Dynamic composition showing fitness and wellness. Motivational and aspirational mood. 16:9 aspect ratio for YouTube thumbnail.`,

    finance: `A professional photo symbolizing financial success with upward trending elements and prosperity imagery. ${styleDescriptor}. Deep blues and golds. Sophisticated business aesthetic with growth symbolism. Professional corporate lighting. 16:9 aspect ratio for YouTube thumbnail.`,
  };

  const basePrompt = nichePrompts[niche] || nichePrompts.manifestation;

  return `${basePrompt}

Context: ${productInfo.substring(0, 150)}

IMPORTANT: 
- 16:9 aspect ratio (YouTube thumbnail)
- High contrast for visibility
- NO text or words in the image
- Eye-catching and scroll-stopping
- Professional quality ${style} style
- Suitable for YouTube advertising`;
}

/**
 * Generate multiple thumbnail variations
 */
export async function generateThumbnailVariations(params: {
  niche: string;
  productInfo: string;
  count: number;
}): Promise<GenerateThumbnailResult[]> {
  const { niche, productInfo, count } = params;
  const styles: Array<"photorealistic" | "illustrated" | "minimal"> = [
    "photorealistic",
    "illustrated",
    "minimal",
  ];

  const thumbnails: GenerateThumbnailResult[] = [];

  for (let i = 0; i < Math.min(count, 3); i++) {
    const style = styles[i % styles.length];
    try {
      const thumbnail = await generateThumbnail({
        niche,
        productInfo,
        style,
      });
      thumbnails.push(thumbnail);
      // Add delay to avoid rate limiting
      if (i < count - 1) {
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    } catch (error) {
      console.error(`Failed to generate thumbnail variation ${i + 1}:`, error);
    }
  }

  return thumbnails;
}
